let anshan2 = {
	width: 37,
	height: 22,
	colors: {
		'A': "#312829",
		'B': "#FFFFFF",
		'C': "#FFD373",
		'D': "#73FFAD",
		'E': "#7382FF",
		'F': "#F7695A",
		'G': "#FFD7C6",
		'Z': "#B5AEA5"
	},
	patterns: [
		/*1*/
		"FCFFFCCFFFFCFFBAEEEEAAAAAAAAAAAAAAZEE"+
		"AFCFFFFFFFCFBBAZAAEAAAAAAAAAAAAABBBZE"+
		"ZAFAAAAAAAFBAAZZZZZAAAAAAAAAAAAABBCBZ"+
		"ZZAACCBBCCAAZZZZZZAAAAAZAZCACAABBCCBB"+
		"ZZZZAAAAAAZZZZZZZZAZAAAAAAAAAAABBBBBB"+
		"ZZZAAAZAZZZZZZZZZZAAAZAAAAAAAZAAABBEA"+
		"ZZAGGAAAAZZZZZZZZZAAAZAAAAAAAGZAZAEFF"+
		"ZAGGACBBCAZZZZZZZZAAZGGGGGGGGGGAAAAFA"+
		"ZAAAAAAAAAAAZZZZZZAAAAAAGGGGAAAAGAAFA"+
		"AFBCFFBCFBCBAZZZZZAAGAAAGGGGGAAAGAAFF"+
		"FFCFFFFFCFFCBAZZZAZAGAABGGGGGAABGAGAF"+
		"FCFFFFFFFCFFCBAZZAZAGAAAGGGGGAAAGGGCF"+
		"FCFFFFFFFCFFFCBAAAAGGGGGGGGGGGGGGGGCA"+
		"FCFFFCFFFCFFFCABAAAGGGGGGGGGGGGGGAAFA"+
		"CFFFCFCFFFCFFCABBBAAGGGGGGAGGGGGAAAFE"+
		"CFFFFCFFFFCFFFCABBBZAAGGGGGGGGAAAAAAE"+
		"CFFFCCCFFFCFFFCABBBBZAAAAEEZEEAAAAAAE"+
		"CFCFFCFFCFCFFFCABBBBCBGABCEECCZAAAAAE"+
		"CFFCFCFCFFCFFFCAZBBCBGABBEECBBEZZAAAA"+
		"CZFFCCCFFFCZFFCAAZZCGGBEEGGECBBEGGAAA"+
		"ZCZFFFFFFCZFFFAZZAAAAABCEEECBBBEGGBAZ"+
		"ZCZFFFFFFCZFAAZZZZZAAABBCCCBBBBABBZAZ",
		/*2*/
		"ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ"+
		"ZZZZZZZZZZZAACCBZZZZZZZZZZZZZZZZZZZZZ"+
		"ZZZZZZZZZZZZZACCBZZZZZZZZZZZZZZZZZZZZ"+
		"ZZZZZZZZZZAAACCBBZZZZZZZZZZZZZZZZZZZZ"+
		"ZZZZZZZZAACCCCCCCBZZZZZZZZZBZZZZZZZZZ"+
		"ZZZZZZZACCCCCCCCCCBZZZZZZZZZCZZZZZZZZ"+
		"ZZZZZZACCCCCCCCCCCCBZZZZZZZZBZZZZBZZZ"+
		"ZZZZZACCCCACCCCCCCACBZZZZBZZZCZZCZZZZ"+
		"ZZZZZACCCCCACCCCCACCBZZZZZCZZZZZBZZZZ"+
		"ZZZZACCCCCCCACCCACCCCBZZZZZBCZZBZZZZZ"+
		"ZZZACCCCCCAACCCCCAACCBZZZZZZZZCZZZZZZ"+
		"ZZACCCCCZZCCCCFFCCCZCBZZZZZZZCZZZZZZZ"+
		"ZACCCCCCCCCCCCCCCCCCCAZZZAZBBBBZZZZZZ"+
		"ZAAACCCCCCCCCCCCCCCCCCAAAZZFFFFAZZZZZ"+
		"ZZZACCCCCCCCCCCCCCCCCCCAZZZFCCCAZZZZZ"+
		"ZZZACCCCCCCCCCCCCCCCCAAZZZZFFFFAZZZZZ"+
		"ZZZACCCCCCCCCCCCCCCCCAZZZZZFFFFAZZZZZ"+
		"ZZZACCCCCCCCCCCCCCCCAZZZZZFFFFFAZZZZZ"+
		"ZZZACCCCCCCCCCCCCCCCAZZZZZFFFFFAZZZZZ"+
		"ZZZZACCCCCCCCCCCCCCCAZZZZZFFFFAZZZZZZ"+
		"ZZZZACCCCCCCCCCCCCCAZZZZZZFFFFAZZZZZZ"+
		"ZZZZZACCCCCCCCCCCCAZZZZZZZFCCCAZZZZZZ",
		/*3*/
		"ZZZZZZZZZZZZZZZZZZZZZAAZZZZZZZZZZZZZZ"+
		"ZZZZZZZZZZZZZZZZZZZZZZZAAAAAAAZZZZZZZ"+
		"ZZZZAAAAAAZZZZZZZZZBBAABBBBBAAAABBAZZ"+
		"AAAAFFFCFCAZZZZZZZBCCABAAAAABBAACCCAZ"+
		"FFFFFFFCFCAZZZZZAACCAAAAAAAAAAAAACCAA"+
		"FFFFFFAAAAAZZZZAAACAAAACACACAAAAAACZA"+
		"AAAAAAZCAZZZZZAAAZAAAAAAACACAAAAAAAAZ"+
		"ZZZZZZFCAZZZZAAZZZACAAGAAAAAAAAACAAAZ"+
		"FFFFFFFCAZZZAZZZZZACAAGGAAAAAGAACAAAZ"+
		"FFFFAFFFCAZZAZZZZZAAAAAAAAAAAAGAAAAAZ"+
		"FAFAAAFFCAZZZAZZZAAAAAAFGGGGAFGAAAAAZ"+
		"FAFFZAFFCAZZZAZAAZAAAGFBGGGGFBGGAAAZA"+
		"AAZAAAAFCAZZZZAZZZAAAGFFGGGGFFGGAAAZA"+
		"FAFFAZFFCAZZZZZZZZAAAGGGGGGGGGGGAAAZZ"+
		"FAFAFAAFCAZAZZZZZZZAAAGGGGFGGGGAAAZZZ"+
		"FFFFFFFFFCAGAZZAAAAAGGGGGGGGGGGGAZZZZ"+
		"FFFZAAAFFCAGGAABBBBBAAZZZACCAAZZZZZZZ"+
		"FFFAFAFFFCAGGAAABBBBBBAAAEAAAAAAZZZZZ"+
		"FFFAAAAFFCAAGAAAZBBBBBBEEEEEEEBBAZZZZ"+
		"CFFFFAFFFCAZAAAAAZZZZZZBCCCCGCCBBAAZZ"+
		"CFAAFAFAFCAZZAAAAAAAAAAEEBBBCBBZBBBAA"+
		"CFFFFFFFFCAZZZZZZZZZZZZAEZBBBBZEABBBB",
		/*4*/
		"ZZZZZZZZZZZZZZAAZZZZZZZZZZZZZZZZZZZZZ"+
		"ZZZZZZZAAAAAAAZZZZZZZZZZZZZZZZZZZZZZZ"+
		"ZZABBAAAABBBBBAABBZZZZZZZZZAAAAAAZZZZ"+
		"ZACCCAABBAAAAABACCBZZZZZZZACFCFFFAAAA"+
		"AACCAAAAAAAAAAAAACCAAZZZZZACFCFFFFFFF"+
		"AZCAAAZAZFAFAFAAACCAAAZZZZAAAAAFFFFFF"+
		"ZAAAZAZZZFAFAAAAAACZAAAZZZZZACZAAAAAA"+
		"ZAAABZZAAAAAAAGAAFAZZZAAZZZZACFZZZZZZ"+
		"ZAAABAAGAAAAAGGAAFAZZZZZAZZZACFFFFFFF"+
		"ZAAAAAGAAAAAAAAAAAAZZZZZAZZACFFFFFFFF"+
		"ZAAAAAGAFGGGGAFAAAAAZZZAZZZACFFAFFZAA"+
		"ZAAAAGGFBGGGGFBGAAAZAAZAZZZACFAAAFAFF"+
		"ZZAAAGGFFGGGGFFGAAAZZZAZZZZACFZAZFAAA"+
		"AZAAAGGGGGGGGGGGAAAZZZZZZZZACFAAAFAZA"+
		"AZZAAAGGGGFGGGGAAAZZZZZZZAZACFAAAFAFA"+
		"AZZZAGGGGGGGGGGGGAAAAAZZAGACFFFAFFFFA"+
		"ZAZZZZZAACCAZZZAABBBBBAAGGACFFFFFAFFF"+
		"ZAZZZAAAAAAFAAABBBBBBAAAGGACFFFAAAAAF"+
		"ZZZZABBCCECCFFBBBBBBZAAAGAACFFFZAAZFF"+
		"ZZAABBAAGAAACBZZZZZZACACAZACFFAAAAAAC"+
		"AABBBZCAACCCFFAAAAAAAAAAZZACFFFAAAAFC"+
		"BBBBZFFCCFFFFAZZZZZZZZZZZZACFFAAZZAAC",
		/*5*/
		"ZZZZAFFFAZZADDDBAZZDZZADDBAZZZZZZZZZZ"+
		"ZZZZZAFAZZZADDBAAADAAADDDBAZZZZZZZZZZ"+
		"ZZAZZZAZZAADDDDDDDDDADDDDBAZZZZZZZAZZ"+
		"ZAFAZZZZABBADDDDDBDDBDDBDBAZZZZZZAFAZ"+
		"AFCAZZZZZAADDDBDDBBDDBDBBBDAZZZZACFFA"+
		"FFCFAZZZABADDDDDDDDDDDDDBBBAZZZZAFCFF"+
		"FCFFFAZZAADDDZZDDDDZDDDDDBDAZZZAFFFCC"+
		"CFFFFAZZADDDAAAGDDDAAAADDDDAZZZAFFFFF"+
		"FFCFFFAZADADZZZGGDDZZZGDDDDAZZZAFFCFF"+
		"FCFCFFAADDAZCZBGGGDCZBGDDDDAZZAFFCFCF"+
		"FFCFFAAADDAGCCCGGGGCCCGDDDDAZAAFFFCFF"+
		"FFFFACCCAAFGGGGGGGGGGGFFDDDDABCAFFFFF"+
		"AFFACCCABAGGGGGGGGGGGGGDDDDABCCCAFFFF"+
		"ZAFACCCABAGGGGGAAGGGGGGADAABACCCAAFFA"+
		"ZZAACCCCBBAAGGGGGGGGGGADAZBBACCCADAAZ"+
		"ZZZACCCABBBZAAAAAAAAAAZAZBBBCCCCADAZZ"+
		"ZZZACCAABBBBZABFCCFABABBBBBBACCCADAZZ"+
		"ZZZACCAABBBBBBAFFGFBAZBBBBBBAACCCAAZZ"+
		"ZZZZACACCZBBBBABGGAAZBBBBZZZZACCCAZZZ"+
		"ZZZZZAAAAAZZBBBAAAABBBBZZAAAAAAAAZZZA"+
		"ZZZZZZZZADAAZBBBABBBBBBAADDDAZZZZZZAF"+
		"ZZZZZZZZADDAZBABBBABBBZADDDDAZZZZZAFF",
		/*6*/
		"ZZZZAAAAFBBBAZZZZAFFFFBFAAZZZZZZZZZZZ"+
		"ZZZAFFFFFFBBBAZZAEBBFFBFBBAZZZZZZZZZZ"+
		"ZZZAFFFFBBBFFBAZAEFFBBFFBFBAZZZZZZZZZ"+
		"ZZAFFBBBFFBFFFBAZAEFFFBBFBBAZZAAZZZZZ"+
		"ZZABBFFFFFBFFBAZZAEFFFBFBBBAZAFFAAZZZ"+
		"ZAEEFBFFFBFFBAZZZZAEFBFFFBAZAFFCFFAAZ"+
		"ZZAAEFBFFBFBAZZZZZAEFBFFBAAAAAACFFFFA"+
		"ZZZZAEFBFFBAZZZZAAAAEFBBAFFFABBAZFFFF"+
		"ZAAAAAEFFBAZZZZZZAAAABAAFFABBBBBAZFFF"+
		"AAAAAAAEFAZZZZZZZZAFFAFFABBBBBBFFAZFF"+
		"ZZAAAAAAAZZZZZAAAAAFFFABBBBBBFFFFFACF"+
		"ZZZZZZZZZZZZAAFFFAFFAABBBBBBFFFFFFFAC"+
		"ZZZZZZZZZZZACFFFFAAABBBBBBFFFFFFFFFFA"+
		"ZZZZZZZZZZZAZCFFAABBBBBBFFFFCCFFFFFFF"+
		"ZZZZZZZZZZZAZFCCABBBBBFFFFFCFFCFFFFFF"+
		"ZZZZZZZZZZZAZFFFABBBBFFFFFFCCFCFFFCFF"+
		"ZZZZZZZZAAAAZFFFFABFFFFFFFFFCCCCFCFFC"+
		"ZZZZAAAAAAAAZFFFFCAZFFFFFFFFFFFCCFFCC"+
		"ZZZAAAAAAAAAAZFFFCFAZFFFFFFFFFCFCFFFC"+
		"ZZZZAAAAAAAAAZFFFFCCAZFFFFFFFCFFFCFFC"+
		"ZZZZZZAAAAAAAZFFFFFCFAZFFFFFFFFCFFCFC"+
		"ZZZZZZZAAAAAAZFFCCCCCCAZFFFFFCCCCCCCC",
		/*7*/
		"ZZZZZZZZZACAFEEAACCCAAZZAAZAAZZZZZZZZ"+
		"ZZZZZZZZAAAEEBBBAAAAZZZACCACCAZAZZZZZ"+
		"ZZZZZZZZAAAFBBAABAAAAZAAACAAACACAZZZZ"+
		"ZZZZZZZAAAAFBBAABAAAAAFFCFFFFFAACAAZZ"+
		"ZAAAAZZAAZFFABBBAAFBCFBFBFBBCBFFAACAA"+
		"AFFFZAAZZFFFFAAAFFBFFCFCFFFFCFFBCFACC"+
		"AFFFFFFFFFFFFFFFFBAEEBCFCFFCFCFCFFCAA"+
		"ZAFFFDFDFDFDFFFFFAEEBFCFCFCFFFCFFBFFA"+
		"ZAFDDBDBDBDBDDFFAABBFCFFFCFFFCFFFCFCF"+
		"ZZAABABABABABADFFFAEEBFFFCFFFCFFAAFBF"+
		"ZZZAAAAAAAAAAADFFAEEBAFAAAAAAAFACCAFB"+
		"ZZZZAZAZAZAAADFFAAEBAAAACCCCCAACCCAZF"+
		"ZZZZZZZZZAABBFFFFAAACCACCCCCACCCCAFFZ"+
		"ZZZZZZZAABBAFFFFAACCCCACCCCCACCCCAZZF"+
		"ZZZZZAABBAFFFFFZAACCCZCCFFCCCCZCCAFFZ"+
		"ZZZAABBAFFFFFFZAACCCCCCCCCCCCCCCCAFZF"+
		"ZZZAFFFFFFFFFZAAACCCCCCCCCCCCCCCCAFFA"+
		"ZZZAAFFFFFFFZAAAACCCCCCCCCCCCCCCCAAAA"+
		"ZZZZZACCFFZAAAAAACCCCCCCCCCCCCCCCAAAA"+
		"ZZZZZZAACZAAAZZACCCCCCCCCCCCCCCCCAAAA"+
		"ZZZZZZZAAAZZZZZACCCCCCCCCCCCCCCCCAAAZ"+
		"ZZZZZZZZZZZZZZZACCCCCCCCCCCCCCCCCAAZZ",
		/*8*/
		"ZAZFAAZZZZZZZZZZAZFFFFAZZZAZFFAZZZZZZ"+
		"AZFFFCAZZAAAAAAAAAZFFFFAAAAAAFFAZZZZZ"+
		"AZFCCBAAAZFFFFFCCFAZFFFFFACAAAFFAZZZZ"+
		"ZACBBFFFFFCFFFCFFAFFFFFFFFACCAFAAZZZZ"+
		"ACBFCCFFCCFCCCFFAFFBBBFFFFFAAFFBAZZZZ"+
		"AFFFFFCCFFFFFFFCAFBABBBBBFFFBBBBBAZZZ"+
		"ACCFFFFFFCFFFFCFABBAAAAAAAFECCBAAAZZZ"+
		"FFFCFFFCCFCFFCFAFCCCABCABAFEECCBCBAZZ"+
		"FFFFCCCFFFFCCFFAFFCCABCCCAFFEEEBCCAZZ"+
		"AFFAAFFFFFFFAFFAFFFFCABBAEFFFFFABAAZZ"+
		"AAACCAZAAAAAAFFFAFFFFCAAEFFFFFFEACAZZ"+
		"AAACCCAACCCCAFFFFAFFFFEEFFFFACAFEAZZZ"+
		"AAAACCCCACCCAFFFFCAFFFFFFFFCCCCFFFAZZ"+
		"AAAACCCCACCCCAFCCCFAFFFFFBBAAABFFFAZZ"+
		"AAAACCCZCCCFFACFFCFABFFBBAABBBABFFAAZ"+
		"AAAACCCCCCCCCCACFFCCABBAABBCCCBABBAAZ"+
		"AAAACCCCCCCCCCAFCCCFABACCCCCCCCCABAAA"+
		"ZAAACCCCCCCCCCACFFCFFAFFBBBBBBBBFAAAA"+
		"ZAAACCCCCCCCCCAFCFFBBAAAFFFFFFFFAAAAA"+
		"ZZAACCCCCCCCCCCAFFBAAAZZAAAAAAAAAAAAZ"+
		"ZZAACCCCCCCCCCCABBAACAZZZZZZZZZZAAAZZ"+
		"ZZZACCCCCCCCCCCCAAACCAZZZZZZZZZZZZZZZ"
	]
};
let albacore1 = {
	width: 37,
	height: 22,
	colors: {
		'A': "#FFFFFF",
		'B': "#352828",
		'C': "#FFD371",
		'D': "#71FFAC",
		'E': "#7181FF",
		'F': "#FF7194",
		'G': "#FBD7C2",
		'Z': "#BAAFAA"
	},
	patterns: [
		/*1*/
		"ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ"+
		"ZZZZZZZZZZZZZZZZZZBBZZZZZZZZZZZZZZZZZ"+
		"ZZZZZZZZZBZZZZZZZBCBZZZZBZZZZZZZZZZZZ"+
		"ZZZZZZZZBZZBZZZZBCCBZZBZZBZZZZZZZZZZZ"+
		"ZZZZZZZBZZBZZZZZBCBZZZZBZZBZZZZZZZZZZ"+
		"ZZZZZZZBZZBZZZZZBCBZZZZBZZBZZZZZZZZZZ"+
		"ZZZZZZZZBZZBZZZZBCBZZZBZZBZZZZZZZZZZZ"+
		"ZZZZZZZZZBZZZZZBCCBZZZZZBZZZZZZZZZZZZ"+
		"ZZZZZZZZZZZZZZZBCBZZZZZZZZZZZZZZZZZZZ"+
		"ZZZZZZZZZZZZZZZBCBZZZZZZZZZZZZZZZZZZZ"+
		"ZZZZZZZZZZZZZZZBCBZZZZZZZZZZZZZZZZZZZ"+
		"ZZZZZZZZZZZZZZZBCBZZZZZZZZZZZZZZZZZZZ"+
		"ZZZZZZZZZZZZBBBBCBBBBBZZZZZZZZZZZZZZZ"+
		"ZZAZZZZZZZBBCCCCCCCCCCBBZZZZZZZZAZZZZ"+
		"ZZZAAZZZZBCACACACCCACCCABZZZZZAAZZZZZ"+
		"ZZZAAAZZBCCCACACCCACBCCCABZZZAAAAZZZZ"+
		"ZZAAAAABCCCCCCCCCCCCGBCCCABZAAAAAAZZZ"+
		"ZZZAAABCCCCCCCCBCCCBGBCCCCABAAAAAZZZZ"+
		"ZZEAEBBCCCCCCCBGCCBAFABCCCCBBBBAAAZZZ"+
		"ZZZEBBCCCBZAFFGGGGGAFFGBCCCCBBEBAEZZZ"+
		"ZZBBEBBCCBGAFFGGGGGAFFGGZCCBBEBAECBZZ"+
		"ZBCCBEBCCBGGGGGGGGGGGGGGZCBBEBCCCCCBZ",
		/*2*/
		"CCCCCCCZCCCCCCCCCCCBZZZZZZZZZZZZZZZZZ"+
		"CCCCCCCZCCCCCCCCCBBZZZZZZBZZZZZZZZZZZ"+
		"CCCCCCCZCCCCCCCCBDBBBZZZZZBZZZZZZZZZZ"+
		"BCCCCCCZCCCCCCBBDDBAABBZZZBZZBZZZZZZZ"+
		"BBBCCCCZCCCCCBADDDBAAAABZZZBZZBZZZZZZ"+
		"BBDBCCCZCCCBBAAADBAAAAAABZZZZZZBZZZZZ"+
		"ZBDDBBCZCCBADDAGBZAAAAACCBZZZZZBZZZZZ"+
		"CZBDDDBCBCAAADBBZCBZAACBCBBZZZZZBZZZZ"+
		"CCZBDDDBABDAGBZZCCCBZACBCCBZZZZZBZZZZ"+
		"CCCZBBBAACBBBZCCCCCBZAACCBBZZZZBZZBZZ"+
		"CCCCZBZACCCBZCCCCCCCBACBCBBZZZZZZZBZZ"+
		"BCCCCBACCCBCCCCCCCCCBZCCCBZZZZZZZBZZZ"+
		"DBCCCBACCBCCCCBCCCCCBBCCBZZZZZZBBZZZZ"+
		"DBCCCCBBBCCCCBBCCCCCBABBZZBBZZZZZZZZZ"+
		"DBCCCCCZCCCCCBCCCCCBFAAZZBAABBZZZZZZZ"+
		"DDBCCCCZCCCCCCCCCBBAFFFABAFBFBZZZZZZZ"+
		"DDBCCCCZCCCCCCCCBFFFAAFBAFFFBBZZZZZZZ"+
		"DDDBCCCZCCCCCCBBFFFFFFABFZFFFBZZZZZZZ"+
		"DDDBCCCZCCCCCBFFFFFFFFFBBFZZZBAZZZZZZ"+
		"ADDDBCCZCCCBBFFFFFFFFFFFFBBBBBAAZZZZZ"+
		"ZADDDBCZCCBAFFFFFFFFFFFFFFAFFFFAAZZZZ"+
		"ZZAAFFBZBBFFAFFFFFFFFFFFAFFAAFFFFAZZZ",
		/*3*/
		"ZZZZZZZZZZZZZBEEEEECCCCCCCBCZBCBCZBZZ"+
		"ZZZZZZZZZZZZZZBECBBBBBBBBBZBBZBZBBZZZ"+
		"ZZZZZZZZZZZZZZZBBCCCCCCCCCCCCCCCCZBZZ"+
		"ZZZZZZZZZZZZZZZBCABCACCACACACCACCCBZZ"+
		"ZZZZZZAZZZZZZZBCABZBCABCACACACCACCBZZ"+
		"ZZZZZZAZZAZZZZBCBZGBCCGBCCCCCCCCCCCBZ"+
		"ZZZZZAAAZZZZZBBCZGGGBCGBCCCCCCCCCCCBZ"+
		"ZZZAAAAAAAZZBEEBGGGGBCGGBCCCCCCCCCCBZ"+
		"ZZZZZAAAZZZZBFFBBBBBGGGBBBBZBCCCCCCBZ"+
		"ZZZZZZAZZZZZZBEBGEEAGGGGEEAGBCCCCCCCB"+
		"ZZZZZZAZZZZZZZBBGEEEGGGGEEEBCACCCACAB"+
		"ZZAZZZAZZZZZZZBCGGGGGGGGGGGBCCCBCCCCB"+
		"ZAAAZZZZZZZZZBCCGGGGGGGGGGBCCCCBCCCCB"+
		"ZZAZZZZZZZZZZBCCGGGGGGGGBGBCCCCBCCCCB"+
		"ZZZZZZZZZZZZZBCBCGGGGBBBGGBCCCBZCCCBZ"+
		"ZZZZZZZZBZZZZZBZBBGGGGGGGGBCCBZCCCBZZ"+
		"ZZZZZZZBBZZZZZZZZZBBBBBBBBBBBBBBBBZZZ"+
		"ZZZZZZZBBZZZZZZZZBFBEBCBEBFBBBBBZZZZZ"+
		"ZZZZZBBZBBZZZZZZZBFBECCCBEFBBBBBZBBZZ"+
		"ZZZZZBBBBBZZZZZZZZBFBBCBEBBFBBEEBZZBZ"+
		"ZZZZZBBBBCBZZZZZBBGBAAAABGGGEBCEEBZBZ"+
		"ZZZZZBBBBCEBZZZBGGBAAAAAABGGGGBCEEBZZ",
		/*4*/
		"ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ"+
		"ZZZZZZZZZZZZZZZZZZZZZZBZZZZZZZZZZZZZZ"+
		"ZZZZZZZZZZZZZZBZZZZZZBZZZZZZZZZZZZZZZ"+
		"ZBBZZZZZZZZZZBZZZZBBZZZZZZZZZZZZZZZZZ"+
		"BACBBBBZZZZZBZZZZBCCCZZZCZZZZZZZZZZZZ"+
		"BCCCCCCBZZZZBZZZBCCCCBCCZZBZZZZZZZZZZ"+
		"CBCCCBCCBZZZZZZBCCCCCCCZZBZZZZZZZZZZZ"+
		"CBCCCBCCBZZZZZBCACCCCCCCZZCZZZZZZZBBB"+
		"CCFFCCCCCBZZZBCACCCCCCCCCCZZZZZZBBCCC"+
		"CCCCCCCCCBZZZBCCCCCCCCCCCCZZZZZBCCCCC"+
		"CCCCCCCCCBZZBCCCCCCCCCCCCCBZZZBCCCCCC"+
		"CCCCCCCBCBZZBCBCCCCCBCCCCBCZZBCCCCCCC"+
		"CCCCCCCCBBZZBCCBCCCBCCCCBCCZZBCCCCCCC"+
		"CCCCCCCCCCBZBCBCCCCCBCCCCCBZBCCCCCCCC"+
		"CCCCCCCCCCBZZBCCFFCCCCCCCCBZBCCCCCCCC"+
		"CCCCCCCCCCBZZZBCCFFCCCCCCCBZBCCCCCCCC"+
		"CCCCCCCCCBZZZZZBCFFCCCCCCBZZBACCCCCCC"+
		"BBBBBBBBBZZZZZZZBBBBBBBBBZZZBBBBBBBBB"+
		"BZBZBZBZBZBZZZBZBZBZBZBZBZBZZBZBZBZBZ"+
		"ZBZBZBZBZBZZZZZBZBZBZBZBZBZZZZBZBZBZB"+
		"ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ"+
		"ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ",
		/*5*/
		"AAAAAAAAAAAAZBBBEABZZZZZZZZZZZZZZZZZZ"+
		"AAAAAAAAAABBBEAAAAABZZZZZZZZZZZZZZZZZ"+
		"AAAAAAAABBEAABAAAAAABZZZZZZBBBBBBBZZZ"+
		"ZAAAAABBAAAEAAZEAAAAABZZZZBGGGGBFBZZZ"+
		"ZZAABBEAZAAAAAGGEAAAABZZZBGGGGBZFFBZZ"+
		"ZZZBEAAAGZAAAAGGGBAAABZZZBBCFAAZZFBZZ"+
		"ZZBEAAAAGGZAAAGGBGGAABZBBFFCCFAAAAZBZ"+
		"BBAEAAAGAGGGAAGBGGGGABBAFFFFCFAAAABBZ"+
		"EZAEAAAGGGGGAGGBBBBGGBBAAFFFAAAABBZZZ"+
		"AAAEAAAGBBBBGGGGGGGGBBAAAFFAAABBBZZZZ"+
		"AAAAEAGGGGGBGGGGGGBBFAAAAAAGGBAABZZZZ"+
		"AAAAAEEGGGBGGGGGBBFFCFBBAABBBAAABZZZZ"+
		"EAAAAAZGGBGGGGGGBFFBBBZZBBAAAAAABZZZZ"+
		"EAAAAAAGGGGGGGGGBBBGGBZZZBAAAAAABZZZZ"+
		"AEAAAAAAAGGGGGGGGGGGBZZZZBAAAAABZZZZZ"+
		"AAZAAAAAAAAGGGGGGGGBABZBBAZAAAABZZZZZ"+
		"AAAEBBAAAAGAGGGGGBBEAABAAAAAAAABZZZZZ"+
		"AAAAEEBAAAGAGGGBBGGGGGBAAAAAABBZZZZZZ"+
		"BAAABEEAAEABBBBGGBGGGGGBAAABBZZZZZZZZ"+
		"EBAAABEAEBGBZZGGGGBGGGGBBBBZZZZZZZZZZ"+
		"EBZAAABEBGGGBGGGAAABGBBBABZZZZZZZZZZZ"+
		"EEBZAAABGGGGBAAAAAAABZBEAABZZZZZZZZZZ",
		/*6*/
		"ZZZBBZBAAAAAABZZZZZZZZBZZBZZZZZZZZZZZ"+
		"ZZBAFBCAAAAAAABZZZZZZBBZZBBZZZZZZZZZZ"+
		"ZBAABCACBAAGBAABZZZZBBBZZBBBZZZZZZZZZ"+
		"AAAABAAABGAABAABZZZZBBBZZBBBZZZZZZZZZ"+
		"ZZABAAAAGGGGGGABZZZZBBBZZBBBZZZZZZZZZ"+
		"ZABZBAAAGGFFGGBZZZZZZBBBBBBZZZZZZZZZZ"+
		"ZZZZZBBABBBBBBZZZZZZZBBBCCZBZZZZZZZZZ"+
		"ZZBBBGGBZZZGGGBBBBZZZZBBZCCBZZZZZZZZZ"+
		"ZBGGGGGGGGGGGGGGGGBZZBBBCZCBZZZZZZZZZ"+
		"BAAZBBGGGGGGGGBBBGABBZZBCCZBZZBDDDBZZ"+
		"BAZEEEBBBBBBBBEEEEAABBCBBBBZZBDDDDDBZ"+
		"ABBBCBAAAAAAAABBCBAAACCBBBZZBDDAADDAB"+
		"BAAZAAZAAZAAZAAZAABAACCBBBZZBDDAADDAB"+
		"BAAZAAZAAZAAZAAZAABBBCCBBBZZBAAADDAAB"+
		"BAAZAAZAAZAAZAAZAABZZBCBBBZZBAAADDAAB"+
		"BAAZAAZAAZAAZAAZAABZZZBBBBZZBAADDAAAB"+
		"BAAZAAZAAZAAZAAZAAABZZBBBBZBAAADDAAAB"+
		"BAAZAAZAAZAAZAAZAAABZZBBBBZZBAAAAAAAB"+
		"BAABAAZAAZAAZAAZABABZZBBBBZZZBADDAABZ"+
		"BBBBBAZAAZAAZAAZABBBZZBBBBZZZZBDDBBZZ"+
		"BCCBBAZAAZAAZAAZABCBZZBBBBZZZZZZZZZZZ"+
		"BBBBBAZBAZBAZBAZABBBZZBBBBZZZZZZZZZZZ",
		/*7*/
		"BBBBZBFFBZCZZCZZCZZZZCZZCZZZZBBFFFFBZ"+
		"AAAABBAFBZZCZZCZZCZZCZZCZZZBBFFFFFFFB"+
		"BBBBABAABCZZCZZCZZZZZZCZZZBFFBBBBBBFF"+
		"AAAZBBAABZCZZCZZZZZZZZZZZBFBBZZBBBBBF"+
		"AAAAABABZZZCZZZBBZZZBBZZBBBZZZBBFFFFF"+
		"AAAAABABBZZZZZBGGBZBGABZZZZZZBFFFFFFF"+
		"AAAAABBAABZZZBGGGBZBGAABZZZBBFFAFAFAF"+
		"AAAAAAAAABZZZBGGGGBGGAABZZBFBFFFAFAFF"+
		"AAZAAAAFFBBZZBGGGGBAAAABZBFFBFFFFZFFF"+
		"AAGZAAAAFABZBGZGGGBAAAZABBFBFZFFZGGFF"+
		"AAGGZAAAAABZBGGGGGBAAAAABFFFZFFFGGGFF"+
		"AAGBBBAAAABZZBGGGGBAAAABZFZFFFFFBGGFF"+
		"GAGGBGAAAABZBAEGGGBAAAAABFBFFFFGBGGFG"+
		"GGGGBGAAAZBBAAZEEBZBZZAAABBFFFFGBGGGG"+
		"GGGGGGAAZBBAEAAEBZZZBAAAAABFFFFGGGGGG"+
		"GGGGGGAAZBAAAEAEBZZBFBAAAAABFFFGGGBGG"+
		"BBGGGAAABEAAAAEEBZBFZFBAAAAABFFGGGGBB"+
		"GGGGGAABAAEAAAAEBZBFZFFBAAAAABFBGGGGG"+
		"BBBZBAABEAAAAAABZZBFFFBZBAAABZBZBBBBB"+
		"GGGBEAABGEAAAAABZZZBFFBZZBABZGGBCCBBB"+
		"GGBEEABGGGBAAAABZZZBFFBZZZBZGGGCEABBA"+
		"EBEECABGGBZBAAZBZZZZBFBZZBFBGCCEEEAEA"
	]
};
let anshan1 = {
	colors: {
		'A': "#FFFFFF",
		'B': "#FFF8E6",
		'C': "#FEF9B7",
		'D': "#EFBD8A",
		'E': "#FFBFC5",
		'F': "#FF3E56",
		'G': "#4D3D3D",
		'Z': "#C9C9C9"
	}
};
let dye = {
	colors: {
		'Bk': "#1D1D21", /*black*/
		'R' : "#B02E26", /*red*/
		'Gr': "#5E7C16", /*green*/
		'Br': "#835432", /*brown*/
		'Bl': "#3C44AA", /*blue*/
		'Pp': "#8932B8", /*purple*/
		'C' : "#169C9C", /*cyan*/
		'Lg': "#9D9D97", /*light gray*/
		'Gy': "#474F52", /*gray*/
		'Pk': "#F38BAA", /*pink*/
		'L' : "#80C71F", /*lime*/
		'Y' : "#FED83D", /*yellow*/
		'Lb': "#3AB3DA", /*light blue*/
		'M' : "#C74EBD", /*magenta*/
		'O' : "#F9801D", /*orange*/
		'W' : "#F9FFFE"  /*white*/
	}
};
